# Generated by Django 3.2 on 2021-04-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findoutapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findoutmodel',
            name='good',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='findoutmodel',
            name='read',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='findoutmodel',
            name='readtext',
            field=models.TextField(blank=True, default='a', null=True),
        ),
    ]
